
/*
 * This file was generated by the SOM Compiler.
 * FileName: ooxcharacter.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_ooxcharacter_h
#define SOM_ooxcharacter_h


/*
 * The SOM_STRICT_IDL macro means that we can ignore stars
 * in our declarations of objects.
 */
#define SOM_STRICT_IDL 1


/*
 * Passthru lines: File: "C.ph", "before"
 */

#include "ooxbase.h"
#include "ooxfield.ih"

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef ooxcharacter
#define ooxcharacter SOMObject
#endif
#include <ooxfield.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#define ex_ooxcharacter_ooxfield_error "::ooxcharacter::ooxfield_error"
typedef
struct ooxcharacter_ooxfield_error {
long  ErrCode;
string  Reason;
} ooxcharacter_ooxfield_error;

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_ex_ooxfield_error
    #ifdef ex_ooxfield_error
        #undef ex_ooxfield_error
        #define SOMTGD_ex_ooxfield_error 1
    #else
        #define ex_ooxfield_error ex_ooxcharacter_ooxfield_error
    #endif /* ex_ooxfield_error */
#endif /* SOMTGD_ex_ooxfield_error */
#ifndef SOMTGD_ooxfield_error
    #ifdef ooxfield_error
        #undef ooxfield_error
        #define SOMTGD_ooxfield_error 1
    #else
        #define ooxfield_error ooxcharacter_ooxfield_error
    #endif /* ooxfield_error */
#endif /* SOMTGD_ooxfield_error */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

#define ooxcharacter_MajorVersion 0
#define ooxcharacter_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define ooxcharacterNewClass c
#pragma linkage(c, system)
#define ooxcharacterClassData d
#define ooxcharacterCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define ooxcharacter_classObj ooxcharacterClassData.classObject
#define _ooxcharacter ooxcharacter_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass  SOMLINK ooxcharacterNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(ooxcharacterNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct ooxcharacterClassDataStructure {
	SOMClass classObject;
	somMToken define;
} SOMDLINK ooxcharacterClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct ooxcharacterCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK ooxcharacterCClassData;

/*
 * New and Renew macros for ooxcharacter
 */
#define ooxcharacterNew() \
   ( _ooxcharacter ? \
	_somNew(_ooxcharacter) \
	: ( ooxcharacterNewClass(\
		ooxcharacter_MajorVersion, \
		ooxcharacter_MinorVersion),\
	   _somNew(_ooxcharacter)))
#define ooxcharacterRenew(buf) \
   ( _ooxcharacter ? \
	_somRenew(_ooxcharacter, buf) \
	: ( ooxcharacterNewClass(\
		ooxcharacter_MajorVersion, \
		ooxcharacter_MinorVersion),\
	   _somRenew(_ooxcharacter, buf)))

/*
 * Override method: somDefaultInit
 */
#define ooxcharacter_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somUninit
 */
#define ooxcharacter_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: define
 */
typedef void   SOMLINK somTP_ooxcharacter_define(ooxcharacter somSelf, Environment *ev, 
		somInitCtrl* ctrl, 
		string name, 
		short length);
#pragma linkage(somTP_ooxcharacter_define, system)
typedef somTP_ooxcharacter_define *somTD_ooxcharacter_define;
#define somMD_ooxcharacter_define "::ooxcharacter::define"
#define ooxcharacter_define(somSelf,ev,ctrl,name,length) \
    (SOM_Resolve(somSelf, ooxcharacter, define) \
	(somSelf,ev,ctrl,name,length))
#ifndef SOMGD_define
    #if (defined(_define) || defined(__define))
        #undef _define
        #undef __define
        #define SOMGD_define 1
    #else
        #define _define ooxcharacter_define
    #endif /* _define */
#endif /* SOMGD_define */

/*
 * Other Constructors for ooxcharacter
 */
static ooxcharacter ooxcharacterNew_define(Environment *ev,string name,short length)
{
   ooxcharacter __somtmp_ooxcharacter;
   if (!_ooxcharacter) ooxcharacterNewClass(ooxcharacter_MajorVersion, ooxcharacter_MinorVersion);
   __somtmp_ooxcharacter = SOMClass_somNewNoInit(_ooxcharacter);
   ooxcharacter_define(__somtmp_ooxcharacter,ev,0,name,length);
   return __somtmp_ooxcharacter;
}

#ifndef SOM_DONT_USE_INHERITED_MACROS
#define ooxcharacter_get_name ooxfield_get_name
#define ooxcharacter_get ooxfield_get
#define ooxcharacter_put ooxfield_put
#define ooxcharacter_get_type ooxfield_get_type
#define ooxcharacter_get_length ooxfield_get_length
#define ooxcharacter_get_dec_point ooxfield_get_dec_point
#define ooxcharacter_somDestruct SOMObject_somDestruct
#define ooxcharacter_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define ooxcharacter_somDefaultAssign SOMObject_somDefaultAssign
#define ooxcharacter_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define ooxcharacter_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define ooxcharacter_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define ooxcharacter_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define ooxcharacter_somDefaultVAssign SOMObject_somDefaultVAssign
#define ooxcharacter_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define ooxcharacter_somInit SOMObject_somInit
#define ooxcharacter_somFree SOMObject_somFree
#define ooxcharacter_somGetClass SOMObject_somGetClass
#define ooxcharacter_somGetClassName SOMObject_somGetClassName
#define ooxcharacter_somGetSize SOMObject_somGetSize
#define ooxcharacter_somIsA SOMObject_somIsA
#define ooxcharacter_somIsInstanceOf SOMObject_somIsInstanceOf
#define ooxcharacter_somRespondsTo SOMObject_somRespondsTo
#define ooxcharacter_somDispatch SOMObject_somDispatch
#define ooxcharacter_somClassDispatch SOMObject_somClassDispatch
#define ooxcharacter_somCastObj SOMObject_somCastObj
#define ooxcharacter_somResetObj SOMObject_somResetObj
#define ooxcharacter_somDispatchV SOMObject_somDispatchV
#define ooxcharacter_somDispatchL SOMObject_somDispatchL
#define ooxcharacter_somDispatchA SOMObject_somDispatchA
#define ooxcharacter_somDispatchD SOMObject_somDispatchD
#define ooxcharacter_somPrintSelf SOMObject_somPrintSelf
#define ooxcharacter_somDumpSelf SOMObject_somDumpSelf
#define ooxcharacter_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_ooxcharacter_h */
