
/*
 * This file was generated by the SOM Compiler.
 * FileName: ooxfield.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_ooxfield_h
#define SOM_ooxfield_h


/*
 * The SOM_STRICT_IDL macro means that we can ignore stars
 * in our declarations of objects.
 */
#define SOM_STRICT_IDL 1


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef ooxfield
#define ooxfield SOMObject
#endif
#include <somobj.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#define ex_ooxfield_ooxfield_error "::ooxfield::ooxfield_error"
typedef
struct ooxfield_ooxfield_error {
long  ErrCode;
string  Reason;
} ooxfield_ooxfield_error;

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_ex_ooxfield_error
    #ifdef ex_ooxfield_error
        #undef ex_ooxfield_error
        #define SOMTGD_ex_ooxfield_error 1
    #else
        #define ex_ooxfield_error ex_ooxfield_ooxfield_error
    #endif /* ex_ooxfield_error */
#endif /* SOMTGD_ex_ooxfield_error */
#ifndef SOMTGD_ooxfield_error
    #ifdef ooxfield_error
        #undef ooxfield_error
        #define SOMTGD_ooxfield_error 1
    #else
        #define ooxfield_error ooxfield_ooxfield_error
    #endif /* ooxfield_error */
#endif /* SOMTGD_ooxfield_error */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

#define ooxfield_MajorVersion 0
#define ooxfield_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define ooxfieldNewClass c
#pragma linkage(c, system)
#define ooxfieldClassData d
#define ooxfieldCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define ooxfield_classObj ooxfieldClassData.classObject
#define _ooxfield ooxfield_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass  SOMLINK ooxfieldNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(ooxfieldNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct ooxfieldClassDataStructure {
	SOMClass classObject;
	somMToken get_type;
	somMToken get_length;
	somMToken get_dec_point;
	somMToken get_name;
	somMToken get;
	somMToken put;
} SOMDLINK ooxfieldClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct ooxfieldCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK ooxfieldCClassData;

/*
 * New and Renew macros for ooxfield
 */
#define ooxfieldNew() \
   ( _ooxfield ? \
	_somNew(_ooxfield) \
	: ( ooxfieldNewClass(\
		ooxfield_MajorVersion, \
		ooxfield_MinorVersion),\
	   _somNew(_ooxfield)))
#define ooxfieldRenew(buf) \
   ( _ooxfield ? \
	_somRenew(_ooxfield, buf) \
	: ( ooxfieldNewClass(\
		ooxfield_MajorVersion, \
		ooxfield_MinorVersion),\
	   _somRenew(_ooxfield, buf)))

/*
 * Override method: somDefaultInit
 */
#define ooxfield_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somUninit
 */
#define ooxfield_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: get_name
 */
typedef string   SOMLINK somTP_ooxfield_get_name(ooxfield somSelf, Environment *ev);
#pragma linkage(somTP_ooxfield_get_name, system)
typedef somTP_ooxfield_get_name *somTD_ooxfield_get_name;
#define somMD_ooxfield_get_name "::ooxfield::get_name"
#define ooxfield_get_name(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxfield, get_name) \
	(somSelf,ev))
#ifndef SOMGD_get_name
    #if (defined(_get_name) || defined(__get_name))
        #undef _get_name
        #undef __get_name
        #define SOMGD_get_name 1
    #else
        #define _get_name ooxfield_get_name
    #endif /* _get_name */
#endif /* SOMGD_get_name */

/*
 * New Method: get
 */
typedef string   SOMLINK somTP_ooxfield_get(ooxfield somSelf, Environment *ev);
#pragma linkage(somTP_ooxfield_get, system)
typedef somTP_ooxfield_get *somTD_ooxfield_get;
#define somMD_ooxfield_get "::ooxfield::get"
#define ooxfield_get(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxfield, get) \
	(somSelf,ev))
#ifndef SOMGD_get
    #if (defined(_get) || defined(__get))
        #undef _get
        #undef __get
        #define SOMGD_get 1
    #else
        #define _get ooxfield_get
    #endif /* _get */
#endif /* SOMGD_get */

/*
 * New Method: put
 */
typedef long   SOMLINK somTP_ooxfield_put(ooxfield somSelf, Environment *ev, 
		string datum);
#pragma linkage(somTP_ooxfield_put, system)
typedef somTP_ooxfield_put *somTD_ooxfield_put;
#define somMD_ooxfield_put "::ooxfield::put"
#define ooxfield_put(somSelf,ev,datum) \
    (SOM_Resolve(somSelf, ooxfield, put) \
	(somSelf,ev,datum))
#ifndef SOMGD_put
    #if (defined(_put) || defined(__put))
        #undef _put
        #undef __put
        #define SOMGD_put 1
    #else
        #define _put ooxfield_put
    #endif /* _put */
#endif /* SOMGD_put */

/*
 * New Method: get_type
 */
typedef char   SOMLINK somTP_ooxfield_get_type(ooxfield somSelf, Environment *ev);
#pragma linkage(somTP_ooxfield_get_type, system)
typedef somTP_ooxfield_get_type *somTD_ooxfield_get_type;
#define somMD_ooxfield_get_type "::ooxfield::get_type"
#define ooxfield_get_type(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxfield, get_type) \
	(somSelf,ev))
#ifndef SOMGD_get_type
    #if (defined(_get_type) || defined(__get_type))
        #undef _get_type
        #undef __get_type
        #define SOMGD_get_type 1
    #else
        #define _get_type ooxfield_get_type
    #endif /* _get_type */
#endif /* SOMGD_get_type */

/*
 * New Method: get_length
 */
typedef short   SOMLINK somTP_ooxfield_get_length(ooxfield somSelf, Environment *ev);
#pragma linkage(somTP_ooxfield_get_length, system)
typedef somTP_ooxfield_get_length *somTD_ooxfield_get_length;
#define somMD_ooxfield_get_length "::ooxfield::get_length"
#define ooxfield_get_length(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxfield, get_length) \
	(somSelf,ev))
#ifndef SOMGD_get_length
    #if (defined(_get_length) || defined(__get_length))
        #undef _get_length
        #undef __get_length
        #define SOMGD_get_length 1
    #else
        #define _get_length ooxfield_get_length
    #endif /* _get_length */
#endif /* SOMGD_get_length */

/*
 * New Method: get_dec_point
 */
typedef short   SOMLINK somTP_ooxfield_get_dec_point(ooxfield somSelf, Environment *ev);
#pragma linkage(somTP_ooxfield_get_dec_point, system)
typedef somTP_ooxfield_get_dec_point *somTD_ooxfield_get_dec_point;
#define somMD_ooxfield_get_dec_point "::ooxfield::get_dec_point"
#define ooxfield_get_dec_point(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxfield, get_dec_point) \
	(somSelf,ev))
#ifndef SOMGD_get_dec_point
    #if (defined(_get_dec_point) || defined(__get_dec_point))
        #undef _get_dec_point
        #undef __get_dec_point
        #define SOMGD_get_dec_point 1
    #else
        #define _get_dec_point ooxfield_get_dec_point
    #endif /* _get_dec_point */
#endif /* SOMGD_get_dec_point */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define ooxfield_somDestruct SOMObject_somDestruct
#define ooxfield_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define ooxfield_somDefaultAssign SOMObject_somDefaultAssign
#define ooxfield_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define ooxfield_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define ooxfield_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define ooxfield_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define ooxfield_somDefaultVAssign SOMObject_somDefaultVAssign
#define ooxfield_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define ooxfield_somInit SOMObject_somInit
#define ooxfield_somFree SOMObject_somFree
#define ooxfield_somGetClass SOMObject_somGetClass
#define ooxfield_somGetClassName SOMObject_somGetClassName
#define ooxfield_somGetSize SOMObject_somGetSize
#define ooxfield_somIsA SOMObject_somIsA
#define ooxfield_somIsInstanceOf SOMObject_somIsInstanceOf
#define ooxfield_somRespondsTo SOMObject_somRespondsTo
#define ooxfield_somDispatch SOMObject_somDispatch
#define ooxfield_somClassDispatch SOMObject_somClassDispatch
#define ooxfield_somCastObj SOMObject_somCastObj
#define ooxfield_somResetObj SOMObject_somResetObj
#define ooxfield_somDispatchV SOMObject_somDispatchV
#define ooxfield_somDispatchL SOMObject_somDispatchL
#define ooxfield_somDispatchA SOMObject_somDispatchA
#define ooxfield_somDispatchD SOMObject_somDispatchD
#define ooxfield_somPrintSelf SOMObject_somPrintSelf
#define ooxfield_somDumpSelf SOMObject_somDumpSelf
#define ooxfield_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_ooxfield_h */
