
/*
 * This file was generated by the SOM Compiler.
 * FileName: ooxlogical.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_ooxlogical_h
#define SOM_ooxlogical_h


/*
 * The SOM_STRICT_IDL macro means that we can ignore stars
 * in our declarations of objects.
 */
#define SOM_STRICT_IDL 1


/*
 * Passthru lines: File: "C.ph", "before"
 */

#include "ooxbase.h"

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef ooxlogical
#define ooxlogical SOMObject
#endif
#include <ooxfield.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#define ex_ooxlogical_ooxfield_error "::ooxlogical::ooxfield_error"
typedef
struct ooxlogical_ooxfield_error {
long  ErrCode;
string  Reason;
} ooxlogical_ooxfield_error;

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_ex_ooxfield_error
    #ifdef ex_ooxfield_error
        #undef ex_ooxfield_error
        #define SOMTGD_ex_ooxfield_error 1
    #else
        #define ex_ooxfield_error ex_ooxlogical_ooxfield_error
    #endif /* ex_ooxfield_error */
#endif /* SOMTGD_ex_ooxfield_error */
#ifndef SOMTGD_ooxfield_error
    #ifdef ooxfield_error
        #undef ooxfield_error
        #define SOMTGD_ooxfield_error 1
    #else
        #define ooxfield_error ooxlogical_ooxfield_error
    #endif /* ooxfield_error */
#endif /* SOMTGD_ooxfield_error */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

#define ooxlogical_MajorVersion 0
#define ooxlogical_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define ooxlogicalNewClass c
#pragma linkage(c, system)
#define ooxlogicalClassData d
#define ooxlogicalCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define ooxlogical_classObj ooxlogicalClassData.classObject
#define _ooxlogical ooxlogical_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass  SOMLINK ooxlogicalNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(ooxlogicalNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct ooxlogicalClassDataStructure {
	SOMClass classObject;
	somMToken define;
	somMToken put_boolean;
	somMToken get_boolean;
} SOMDLINK ooxlogicalClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct ooxlogicalCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK ooxlogicalCClassData;

/*
 * New and Renew macros for ooxlogical
 */
#define ooxlogicalNew() \
   ( _ooxlogical ? \
	_somNew(_ooxlogical) \
	: ( ooxlogicalNewClass(\
		ooxlogical_MajorVersion, \
		ooxlogical_MinorVersion),\
	   _somNew(_ooxlogical)))
#define ooxlogicalRenew(buf) \
   ( _ooxlogical ? \
	_somRenew(_ooxlogical, buf) \
	: ( ooxlogicalNewClass(\
		ooxlogical_MajorVersion, \
		ooxlogical_MinorVersion),\
	   _somRenew(_ooxlogical, buf)))

/*
 * Override method: somDefaultInit
 */
#define ooxlogical_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somUninit
 */
#define ooxlogical_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: define
 */
typedef void   SOMLINK somTP_ooxlogical_define(ooxlogical somSelf, Environment *ev, 
		somInitCtrl* ctrl, 
		string name);
#pragma linkage(somTP_ooxlogical_define, system)
typedef somTP_ooxlogical_define *somTD_ooxlogical_define;
#define somMD_ooxlogical_define "::ooxlogical::define"
#define ooxlogical_define(somSelf,ev,ctrl,name) \
    (SOM_Resolve(somSelf, ooxlogical, define) \
	(somSelf,ev,ctrl,name))
#ifndef SOMGD_define
    #if (defined(_define) || defined(__define))
        #undef _define
        #undef __define
        #define SOMGD_define 1
    #else
        #define _define ooxlogical_define
    #endif /* _define */
#endif /* SOMGD_define */

/*
 * New Method: put_boolean
 */
typedef void   SOMLINK somTP_ooxlogical_put_boolean(ooxlogical somSelf, Environment *ev, 
		boolean booleanv);
#pragma linkage(somTP_ooxlogical_put_boolean, system)
typedef somTP_ooxlogical_put_boolean *somTD_ooxlogical_put_boolean;
#define somMD_ooxlogical_put_boolean "::ooxlogical::put_boolean"
#define ooxlogical_put_boolean(somSelf,ev,booleanv) \
    (SOM_Resolve(somSelf, ooxlogical, put_boolean) \
	(somSelf,ev,booleanv))
#ifndef SOMGD_put_boolean
    #if (defined(_put_boolean) || defined(__put_boolean))
        #undef _put_boolean
        #undef __put_boolean
        #define SOMGD_put_boolean 1
    #else
        #define _put_boolean ooxlogical_put_boolean
    #endif /* _put_boolean */
#endif /* SOMGD_put_boolean */

/*
 * New Method: get_boolean
 */
typedef boolean   SOMLINK somTP_ooxlogical_get_boolean(ooxlogical somSelf, Environment *ev);
#pragma linkage(somTP_ooxlogical_get_boolean, system)
typedef somTP_ooxlogical_get_boolean *somTD_ooxlogical_get_boolean;
#define somMD_ooxlogical_get_boolean "::ooxlogical::get_boolean"
#define ooxlogical_get_boolean(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxlogical, get_boolean) \
	(somSelf,ev))
#ifndef SOMGD_get_boolean
    #if (defined(_get_boolean) || defined(__get_boolean))
        #undef _get_boolean
        #undef __get_boolean
        #define SOMGD_get_boolean 1
    #else
        #define _get_boolean ooxlogical_get_boolean
    #endif /* _get_boolean */
#endif /* SOMGD_get_boolean */

/*
 * Other Constructors for ooxlogical
 */
static ooxlogical ooxlogicalNew_define(Environment *ev,string name)
{
   ooxlogical __somtmp_ooxlogical;
   if (!_ooxlogical) ooxlogicalNewClass(ooxlogical_MajorVersion, ooxlogical_MinorVersion);
   __somtmp_ooxlogical = SOMClass_somNewNoInit(_ooxlogical);
   ooxlogical_define(__somtmp_ooxlogical,ev,0,name);
   return __somtmp_ooxlogical;
}

#ifndef SOM_DONT_USE_INHERITED_MACROS
#define ooxlogical_get_name ooxfield_get_name
#define ooxlogical_get ooxfield_get
#define ooxlogical_put ooxfield_put
#define ooxlogical_get_type ooxfield_get_type
#define ooxlogical_get_length ooxfield_get_length
#define ooxlogical_get_dec_point ooxfield_get_dec_point
#define ooxlogical_somDestruct SOMObject_somDestruct
#define ooxlogical_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define ooxlogical_somDefaultAssign SOMObject_somDefaultAssign
#define ooxlogical_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define ooxlogical_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define ooxlogical_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define ooxlogical_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define ooxlogical_somDefaultVAssign SOMObject_somDefaultVAssign
#define ooxlogical_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define ooxlogical_somInit SOMObject_somInit
#define ooxlogical_somFree SOMObject_somFree
#define ooxlogical_somGetClass SOMObject_somGetClass
#define ooxlogical_somGetClassName SOMObject_somGetClassName
#define ooxlogical_somGetSize SOMObject_somGetSize
#define ooxlogical_somIsA SOMObject_somIsA
#define ooxlogical_somIsInstanceOf SOMObject_somIsInstanceOf
#define ooxlogical_somRespondsTo SOMObject_somRespondsTo
#define ooxlogical_somDispatch SOMObject_somDispatch
#define ooxlogical_somClassDispatch SOMObject_somClassDispatch
#define ooxlogical_somCastObj SOMObject_somCastObj
#define ooxlogical_somResetObj SOMObject_somResetObj
#define ooxlogical_somDispatchV SOMObject_somDispatchV
#define ooxlogical_somDispatchL SOMObject_somDispatchL
#define ooxlogical_somDispatchA SOMObject_somDispatchA
#define ooxlogical_somDispatchD SOMObject_somDispatchD
#define ooxlogical_somPrintSelf SOMObject_somPrintSelf
#define ooxlogical_somDumpSelf SOMObject_somDumpSelf
#define ooxlogical_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_ooxlogical_h */
