
/*
 * This file was generated by the SOM Compiler.
 * FileName: ooxnumeric.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_ooxnumeric_h
#define SOM_ooxnumeric_h


/*
 * The SOM_STRICT_IDL macro means that we can ignore stars
 * in our declarations of objects.
 */
#define SOM_STRICT_IDL 1


/*
 * Passthru lines: File: "C.ph", "before"
 */

#include "ooxfield.ih"

#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef ooxnumeric
#define ooxnumeric SOMObject
#endif
#include <ooxfield.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#define ex_ooxnumeric_ooxfield_error "::ooxnumeric::ooxfield_error"
typedef
struct ooxnumeric_ooxfield_error {
long  ErrCode;
string  Reason;
} ooxnumeric_ooxfield_error;

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_ex_ooxfield_error
    #ifdef ex_ooxfield_error
        #undef ex_ooxfield_error
        #define SOMTGD_ex_ooxfield_error 1
    #else
        #define ex_ooxfield_error ex_ooxnumeric_ooxfield_error
    #endif /* ex_ooxfield_error */
#endif /* SOMTGD_ex_ooxfield_error */
#ifndef SOMTGD_ooxfield_error
    #ifdef ooxfield_error
        #undef ooxfield_error
        #define SOMTGD_ooxfield_error 1
    #else
        #define ooxfield_error ooxnumeric_ooxfield_error
    #endif /* ooxfield_error */
#endif /* SOMTGD_ooxfield_error */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

#define ooxnumeric_MajorVersion 0
#define ooxnumeric_MinorVersion 0

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define ooxnumericNewClass c
#pragma linkage(c, system)
#define ooxnumericClassData d
#define ooxnumericCClassData x
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define ooxnumeric_classObj ooxnumericClassData.classObject
#define _ooxnumeric ooxnumeric_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass  SOMLINK ooxnumericNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(ooxnumericNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct ooxnumericClassDataStructure {
	SOMClass classObject;
	somMToken define;
	somMToken put_long;
	somMToken put_float;
	somMToken get_long;
	somMToken get_float;
} SOMDLINK ooxnumericClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct ooxnumericCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK ooxnumericCClassData;

/*
 * New and Renew macros for ooxnumeric
 */
#define ooxnumericNew() \
   ( _ooxnumeric ? \
	_somNew(_ooxnumeric) \
	: ( ooxnumericNewClass(\
		ooxnumeric_MajorVersion, \
		ooxnumeric_MinorVersion),\
	   _somNew(_ooxnumeric)))
#define ooxnumericRenew(buf) \
   ( _ooxnumeric ? \
	_somRenew(_ooxnumeric, buf) \
	: ( ooxnumericNewClass(\
		ooxnumeric_MajorVersion, \
		ooxnumeric_MinorVersion),\
	   _somRenew(_ooxnumeric, buf)))

/*
 * Override method: somDefaultInit
 */
#define ooxnumeric_somDefaultInit(somSelf,ctrl) \
	SOMObject_somDefaultInit(somSelf,ctrl)

/*
 * Override method: somUninit
 */
#define ooxnumeric_somUninit(somSelf) \
	SOMObject_somUninit(somSelf)

/*
 * New Method: define
 */
typedef void   SOMLINK somTP_ooxnumeric_define(ooxnumeric somSelf, Environment *ev, 
		somInitCtrl* ctrl, 
		string name, 
		short length, 
		short decimal);
#pragma linkage(somTP_ooxnumeric_define, system)
typedef somTP_ooxnumeric_define *somTD_ooxnumeric_define;
#define somMD_ooxnumeric_define "::ooxnumeric::define"
#define ooxnumeric_define(somSelf,ev,ctrl,name,length,decimal) \
    (SOM_Resolve(somSelf, ooxnumeric, define) \
	(somSelf,ev,ctrl,name,length,decimal))
#ifndef SOMGD_define
    #if (defined(_define) || defined(__define))
        #undef _define
        #undef __define
        #define SOMGD_define 1
    #else
        #define _define ooxnumeric_define
    #endif /* _define */
#endif /* SOMGD_define */

/*
 * New Method: put_long
 */
typedef void   SOMLINK somTP_ooxnumeric_put_long(ooxnumeric somSelf, Environment *ev, 
		long longv);
#pragma linkage(somTP_ooxnumeric_put_long, system)
typedef somTP_ooxnumeric_put_long *somTD_ooxnumeric_put_long;
#define somMD_ooxnumeric_put_long "::ooxnumeric::put_long"
#define ooxnumeric_put_long(somSelf,ev,longv) \
    (SOM_Resolve(somSelf, ooxnumeric, put_long) \
	(somSelf,ev,longv))
#ifndef SOMGD_put_long
    #if (defined(_put_long) || defined(__put_long))
        #undef _put_long
        #undef __put_long
        #define SOMGD_put_long 1
    #else
        #define _put_long ooxnumeric_put_long
    #endif /* _put_long */
#endif /* SOMGD_put_long */

/*
 * New Method: put_float
 */
typedef void   SOMLINK somTP_ooxnumeric_put_float(ooxnumeric somSelf, Environment *ev, 
		float floatv);
#pragma linkage(somTP_ooxnumeric_put_float, system)
typedef somTP_ooxnumeric_put_float *somTD_ooxnumeric_put_float;
#define somMD_ooxnumeric_put_float "::ooxnumeric::put_float"
#define ooxnumeric_put_float(somSelf,ev,floatv) \
    (SOM_Resolve(somSelf, ooxnumeric, put_float) \
	(somSelf,ev,floatv))
#ifndef SOMGD_put_float
    #if (defined(_put_float) || defined(__put_float))
        #undef _put_float
        #undef __put_float
        #define SOMGD_put_float 1
    #else
        #define _put_float ooxnumeric_put_float
    #endif /* _put_float */
#endif /* SOMGD_put_float */

/*
 * New Method: get_long
 */
typedef long   SOMLINK somTP_ooxnumeric_get_long(ooxnumeric somSelf, Environment *ev);
#pragma linkage(somTP_ooxnumeric_get_long, system)
typedef somTP_ooxnumeric_get_long *somTD_ooxnumeric_get_long;
#define somMD_ooxnumeric_get_long "::ooxnumeric::get_long"
#define ooxnumeric_get_long(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxnumeric, get_long) \
	(somSelf,ev))
#ifndef SOMGD_get_long
    #if (defined(_get_long) || defined(__get_long))
        #undef _get_long
        #undef __get_long
        #define SOMGD_get_long 1
    #else
        #define _get_long ooxnumeric_get_long
    #endif /* _get_long */
#endif /* SOMGD_get_long */

/*
 * New Method: get_float
 */
typedef float   SOMLINK somTP_ooxnumeric_get_float(ooxnumeric somSelf, Environment *ev);
#pragma linkage(somTP_ooxnumeric_get_float, system)
typedef somTP_ooxnumeric_get_float *somTD_ooxnumeric_get_float;
#define somMD_ooxnumeric_get_float "::ooxnumeric::get_float"
#define ooxnumeric_get_float(somSelf,ev) \
    (SOM_Resolve(somSelf, ooxnumeric, get_float) \
	(somSelf,ev))
#ifndef SOMGD_get_float
    #if (defined(_get_float) || defined(__get_float))
        #undef _get_float
        #undef __get_float
        #define SOMGD_get_float 1
    #else
        #define _get_float ooxnumeric_get_float
    #endif /* _get_float */
#endif /* SOMGD_get_float */

/*
 * Other Constructors for ooxnumeric
 */
static ooxnumeric ooxnumericNew_define(Environment *ev,string name,short length,short decimal)
{
   ooxnumeric __somtmp_ooxnumeric;
   if (!_ooxnumeric) ooxnumericNewClass(ooxnumeric_MajorVersion, ooxnumeric_MinorVersion);
   __somtmp_ooxnumeric = SOMClass_somNewNoInit(_ooxnumeric);
   ooxnumeric_define(__somtmp_ooxnumeric,ev,0,name,length,decimal);
   return __somtmp_ooxnumeric;
}

#ifndef SOM_DONT_USE_INHERITED_MACROS
#define ooxnumeric_get_name ooxfield_get_name
#define ooxnumeric_get ooxfield_get
#define ooxnumeric_put ooxfield_put
#define ooxnumeric_get_type ooxfield_get_type
#define ooxnumeric_get_length ooxfield_get_length
#define ooxnumeric_get_dec_point ooxfield_get_dec_point
#define ooxnumeric_somDestruct SOMObject_somDestruct
#define ooxnumeric_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define ooxnumeric_somDefaultAssign SOMObject_somDefaultAssign
#define ooxnumeric_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define ooxnumeric_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define ooxnumeric_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define ooxnumeric_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define ooxnumeric_somDefaultVAssign SOMObject_somDefaultVAssign
#define ooxnumeric_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define ooxnumeric_somInit SOMObject_somInit
#define ooxnumeric_somFree SOMObject_somFree
#define ooxnumeric_somGetClass SOMObject_somGetClass
#define ooxnumeric_somGetClassName SOMObject_somGetClassName
#define ooxnumeric_somGetSize SOMObject_somGetSize
#define ooxnumeric_somIsA SOMObject_somIsA
#define ooxnumeric_somIsInstanceOf SOMObject_somIsInstanceOf
#define ooxnumeric_somRespondsTo SOMObject_somRespondsTo
#define ooxnumeric_somDispatch SOMObject_somDispatch
#define ooxnumeric_somClassDispatch SOMObject_somClassDispatch
#define ooxnumeric_somCastObj SOMObject_somCastObj
#define ooxnumeric_somResetObj SOMObject_somResetObj
#define ooxnumeric_somDispatchV SOMObject_somDispatchV
#define ooxnumeric_somDispatchL SOMObject_somDispatchL
#define ooxnumeric_somDispatchA SOMObject_somDispatchA
#define ooxnumeric_somDispatchD SOMObject_somDispatchD
#define ooxnumeric_somPrintSelf SOMObject_somPrintSelf
#define ooxnumeric_somDumpSelf SOMObject_somDumpSelf
#define ooxnumeric_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_ooxnumeric_h */
